#!/bin/bash
selection=$CAJA_SCRIPT_SELECTED_FILE_PATHS
echo "$selection" | while read line
do
    cd "$line" && (mv --backup=numbered -f * ../ ; cd .. ; rmdir "$(echo $line | sed -e "s/\n//g")")
done
