#!/bin/bash
# 20-03-2016 - Titanio
# Web: http://tetratitanio.blogspot.com/
# Licencia: GNU General Public License.
# Instalación: Solo funciona en "Caja", copia este archivo en el directorio ~/.config/caja/scripts y otorgarle permisos de ejecución.
# El script otorga permisos de ejecución al archivo seleccionado.
# Útil para darle permisos a los scripts de CAJA y a cualquier archivo ejecutable descargado de Internet.

path=$CAJA_SCRIPT_SELECTED_FILE_PATHS
path=${path%?}
quoted="file://$path"
if [[ -x $path ]]
then
    notify-send -t 2000 "make exec" "$path est déjà exécutable"
else
    chmod +x "$path"
    if [[ -x $path ]]
    then
        notify-send -t 2000 "make exec" "$path est désormais exécutable"
    else
        notify-send -t 2000 "make exec" "échec de l'opération"
    fi
fi
